function(SetupConfig)
	if(WIN32)
		add_compile_definitions(MAGE_WINDOWS)
	elseif(UNIX)
		add_compile_definitions(MAGE_LINUX)
	endif()

	if(WIN32)
		add_compile_definitions(FORCEINLINE=__forceinline)
		add_compile_definitions(NODISCARD=_NODISCARD)
		add_compile_definitions(NULLPTR=decltype\(nullptr\)\(\))
		add_compile_definitions(RESTRICT=__restrict)
	elseif(UNIX)
		add_compile_definitions(FORCEINLINE=inline)
		add_compile_definitions(NODISCARD=\[\[nodiscard\]\])
		add_compile_definitions(NULLPTR=nullptr)
		add_compile_definitions(RESTRICT=__restrict__)
	endif()

	if(CMAKE_BUILD_TYPE STREQUAL "Debug")
		add_compile_definitions(MAGE_DEBUG)
	endif()

	if(CMAKE_BUILD_TYPE STREQUAL "Release")
		add_compile_definitions(MAGE_RELEASE)
	endif()
endfunction()