function(SetupConfig)
	if(WIN32)
		add_compile_definitions(MAGE_WINDOWS)
	elseif(UNIX)
		add_compile_definitions(MAGE_LINUX)
	endif()

	if(WIN32)
		add_compile_definitions(FORCEINLINE=__forceinline)
		add_compile_definitions(NOINLINE=__declspec\(noinline\))
		add_compile_definitions(INLINE=__inline)
		add_compile_definitions(NULLPTR=decltype\(nullptr\)\(\))
		add_compile_definitions(RESTRICT=__restrict)
	elseif(UNIX)
		add_compile_definitions(FORCEINLINE=__attribute__\(\(always_inline\)\))
		add_compile_definitions(NOINLINE=__attribute__\(\(noinline\)\))
		add_compile_definitions(INLINE=inline)
		add_compile_definitions(NULLPTR=nullptr)
		add_compile_definitions(RESTRICT=__restrict__)
	endif()

	if(CMAKE_BUILD_TYPE STREQUAL "Debug")
		add_compile_definitions(MAGE_DEBUG)
	endif()

	if(CMAKE_BUILD_TYPE STREQUAL "Release")
		add_compile_definitions(MAGE_RELEASE)
	endif()

	if(WIN32)
		set(CMAKE_CXX_COMPILER MSVC)
	elseif(UNIX)
		set(CMAKE_CXX_COMPILER g++)
	endif()
endfunction()