function(SetupConfig)
	if(WIN32)
		add_compile_definitions(DELUSION_WINDOWS)
	elseif(UNIX)
		add_compile_definitions(DELUSION_LINUX)
		set(CMAKE_CXX_COMPILER g++)
	endif()

	if(WIN32)
		add_compile_definitions(FORCEINLINE=__forceinline)
		add_compile_definitions(NOINLINE=__declspec\(noinline\))
		add_compile_definitions(INLINE=__inline)
		add_compile_definitions(NULLPTR=decltype\(nullptr\)\(\))
		add_compile_definitions(RESTRICT=__restrict)
		add_compile_definitions(NODISCARD=\[\[nodiscard\]\])
	elseif(UNIX)
		add_compile_definitions(FORCEINLINE=__attribute__\(\(always_inline\)\))
		add_compile_definitions(NOINLINE=__attribute__\(\(noinline\)\))
		add_compile_definitions(INLINE=inline)
		add_compile_definitions(NULLPTR=nullptr)
		add_compile_definitions(RESTRICT=__restrict__)
		add_compile_definitions(NODISCARD=\[\[nodiscard\]\])
	endif()

	if(CMAKE_BUILD_TYPE STREQUAL "Debug")
		add_compile_definitions(DELUSION_DEBUG)
	endif()

	if(CMAKE_BUILD_TYPE STREQUAL "Release")
		add_compile_definitions(DELUSION_RELEASE)
	endif()

	set(LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/Binaries")
	set(RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/Binaries")
endfunction()